version: '3'
services:
  reactapp:
    build:
      context: .
    volumes:
      - ./app:/app
      - /app/node_modules/
      - ./build_results:/build_results
    command: yarn start
    ports:
      - "3000:3000"
